---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-lb
  namespace: default
spec:
  selector:
    matchLabels:
      run: nginx-lb
  replicas: 4
  template:
    metadata:
      annotations:
        v1.multus-cni.io/default-network: kube-system/ipvlan-eth0
        k8s.v1.cni.cncf.io/networks: kube-system/ipvlan-eth1
        ipam.spidernet.io/ippools: |-
          [{"interface": "eth0", "ipv4": ["172-31-64-0"]},
           {"interface": "net1", "ipv4": ["172-31-96-0"]}]
      labels:
        run: nginx-lb
    spec:
      containers:
      - name: nginx-lb
        image: nginx
        ports:
        - containerPort: 80
