---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox
  namespace: default
spec:
  selector:
    matchLabels:
      run: busybox
  replicas: 4
  template:
    metadata:
      annotations:
        v1.multus-cni.io/default-network: kube-system/ipvlan-eth0
        k8s.v1.cni.cncf.io/networks: kube-system/ipvlan-eth1
        ipam.spidernet.io/ippools: |-
          [{"interface": "eth0", "ipv4": ["172-31-64-0"]},
           {"interface": "net1", "ipv4": ["172-31-96-0"]}]
      labels:
        run: busybox
    spec:
      containers:
        - name: ippool-test
          image: busybox
          imagePullPolicy: IfNotPresent
          command: ["/bin/sh", "-c", "trap : TERM INT; sleep infinity & wait"]
