---
- name: Configure spiderpool
  hosts: localhost
  become: false
  gather_facts: false
  tags:
    - deploy
  environment:
    KUBECONFIG: "../kubeconfig"
  tasks:
    - name: Add spiderpool repo with helm
      kubernetes.core.helm_repository:
        name: spiderpool
        repo_url: https://spidernet-io.github.io/spiderpool

    - name: Install spiderpool with helm
      kubernetes.core.helm:
        name: spiderpool
        chart_ref: spiderpool/spiderpool
        namespace: kube-system
        set_values:
          - value: ipam.enableStatefulSet=false
          - value: multus.multusCNI.defaultCniCRName="ipvlan-eth0"

    - name: Pause for 30 seconds
      ansible.builtin.pause:
        seconds: 30

    - name: Remove default SpiderMultusConfig
      kubernetes.core.k8s:
        api_version: "spiderpool.spidernet.io/v2beta1"
        kind: SpiderMultusConfig
        namespace: kube-system
        name: ipvlan-eth0
        state: absent

    - name: Apply custom Spiderpool Multus ipvlan config
      kubernetes.core.k8s:
        definition: "{{ lookup('file', '../manifests/SpiderMultusConfig.yaml') | from_yaml_all }}"
        state: present

    - name: Add Spiderpool IP pools
      kubernetes.core.k8s:
        definition: "{{ lookup('file', '../manifests/SpiderIPPool.yaml') | from_yaml_all }}"
        state: present

    - name: Pause for 10 seconds
      ansible.builtin.pause:
        seconds: 10

- name: Print Spiderpool IP pools
  hosts: localhost
  become: false
  gather_facts: false
  tags:
    - print
  environment:
    KUBECONFIG: "../kubeconfig"
  tasks:
    - name: Get Spiderpool IP pools
      ansible.builtin.command: kubectl get spiderippools.spiderpool.spidernet.io
      register: kubectl_get_spiderippools
      changed_when: false

    - name: Print Spiderpool IP pools
      ansible.builtin.debug:
        var: kubectl_get_spiderippools.stdout_lines
