---
- name: Configure master
  hosts: master
  become: false
  gather_facts: false
  tags:
    - master
  tasks:
    - name: Check if helm is installed
      ansible.builtin.command: which helm
      register: which_helm
      ignore_errors: true
      failed_when: false
      changed_when: false

    - name: Download and install helm
      when: which_helm.rc != 0
      block:
        - name: Download helm installation script
          ansible.builtin.get_url:
            url: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
            dest: /home/ec2-user/get-helm-3.sh
            mode: "0700"

        - name: Install helm
          ansible.builtin.command: /home/ec2-user/get-helm-3.sh
          changed_when: true

    - name: Add spiderpool repo with helm
      kubernetes.core.helm_repository:
        name: spiderpool
        repo_url: https://spidernet-io.github.io/spiderpool

    - name: Install spiderpool with helm
      kubernetes.core.helm:
        name: spiderpool
        chart_ref: spiderpool/spiderpool
        namespace: kube-system
        set_values:
          - value: ipam.enableStatefulSet=false
          - value: multus.multusCNI.defaultCniCRName="ipvlan-eth0"

    - name: Remove default SpiderMultusConfig
      kubernetes.core.k8s:
        api_version: ""
        kind: SpiderMultusConfig
        namespace: kube-system
        name: ipvlan-eth0
        state: absent

    # - name: Apply custom SpiderMultusConfig
    #   kubernetes.core.k8s:
