---
- name: Deploy apps
  hosts: localhost
  become: false
  gather_facts: false
  tags:
    - deploy-apps
  environment:
    KUBECONFIG: "../kubeconfig"
  tasks:
    - name: Create busybox deployment
      kubernetes.core.k8s:
        definition: "{{ lookup('file', '../manifests/Deployment-busybox.yaml') | from_yaml_all }}"
        state: present

    - name: Pause for 30 seconds
      ansible.builtin.pause:
        seconds: 30

    - name: Create nginx deployment
      kubernetes.core.k8s:
        definition: "{{ lookup('file', '../manifests/Deployment-nginx.yaml') | from_yaml_all }}"
        state: present

    - name: Pause for 30 seconds
      ansible.builtin.pause:
        seconds: 30

- name: Print Spiderpool IP pools
  hosts: localhost
  become: false
  gather_facts: false
  tags:
    - print
  environment:
    KUBECONFIG: "../kubeconfig"
  tasks:
    - name: Get pods
      ansible.builtin.command: kubectl get pods -owide
      register: kubectl_get_pods
      changed_when: false

    - name: Get Spiderpool IP pools
      ansible.builtin.command: kubectl get spiderippools.spiderpool.spidernet.io
      register: kubectl_get_spiderippools
      changed_when: false

    - name: Get busybox pod names
      ansible.builtin.command: kubectl get pods -oNAME --selector=run=busybox
      register: busybox_pod_names
      changed_when: false

    - name: Get IPs from inside of busybox pods
      ansible.builtin.command: "kubectl exec -it {{ item }} -- ip -4 addr show scope global"
      loop: "{{ busybox_pod_names.stdout_lines }}"
      register: busybox_pods_ips
      changed_when: false
      ignore_errors: true

    - name: Print pods
      ansible.builtin.debug:
        var: kubectl_get_pods.stdout_lines

    - name: Print Spiderpool IP pools
      ansible.builtin.debug:
        var: kubectl_get_spiderippools.stdout_lines

    - name: Print IPs from inside of pods
      ansible.builtin.debug:
        msg: "{{ item.stdout_lines }}"
      loop_control:
        label: "{{ item.item }}"
      loop: "{{ busybox_pods_ips.results }}"
