---
- name: Configure bastion
  hosts: bastion
  remote_user: ec2-user
  become: true
  gather_facts: true
  tasks:
    - name: Ensure .ssh directory exists
      ansible.builtin.file:
        dest: "/home/ec2-user/.ssh"
        mode: "0700"
        owner: ec2-user
        state: directory

    - name: Install ssh key
      ansible.builtin.copy:
        src: "../id_ed25519"
        dest: "/home/ec2-user/.ssh/id_ed25519"
        mode: "0400"
        owner: ec2-user

    - name: Install vim, tmux, git
      ansible.builtin.dnf:
        name:
          - vim
          - tmux
          - git
        state: present

- name: Configure cluster
  hosts: cluster
  remote_user: ec2-user
  become: true
  gather_facts: true
  tasks:
    - name: Install vim, tmux, git
      ansible.builtin.dnf:
        name:
          - vim
          - tmux
          - git
        state: present

    - name: Set SELinux in permissive mode
      ansible.builtin.shell: |
        setenforce 0
        sed -i 's/^SELINUX=enforcing$/SELINUX=permissive/' /etc/selinux/config

    - name: Add Kubernetes yum repo
      ansible.builtin.yum_repository:
        name: kubernets
        description: Kubernetes repo
        baseurl: https://pkgs.k8s.io/core:/stable:/v1.30/rpm/
        enabled: true
        gpgkey: https://pkgs.k8s.io/core:/stable:/v1.30/rpm/repodata/repomd.xml.key
        gpgcheck: true

    - name: Install kubelet, kubeadm and kubectl
      ansible.builtin.dnf:
        name:
          - kubelet
          - kubeadm
          - kubectl

- name: Configure master
  hosts: master
  remote_user: ec2-user
  become: true
  gather_facts: true
  tasks:
    - name: Initialize kubernetes master
      ansible.builtin.command: kubeadm init

    - name: Install helm
      ansible.builtin.shell: curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

    - name: Add spiderpool repo with helm
      kubernetes.core.helm_repository:
        name: spiderpool
        repo_url: https://spidernet-io.github.io/spiderpool
        force_update: true

    - name: Install spiderpool with helm
      kubernetes.core.helm:
        name: spiderpool
        chart_ref: spiderpool/spiderpool
        namespace: kube-system
        set_values:
          - value: ipam.enableStatefulSet=false
          - value: multus.multusCNI.defaultCniCRName="ipvlan-ens5"
#         - name: Install docker
#           ansible.builtin.dnf:
#             name: docker
#             state: present

#         - name: Add ec2-user to docker group
#           user:
#             name: ec2-user
#             groups: docker

#         - name: Start docker
#           service:
#             name: docker.socket
#             state: started

#         - name: Add kubernets yum repos
#           yum_repository:
#             name: kubernets
#             description: Kubernetes repo
#             baseurl: https://pkgs.k8s.io/core:/stable:/v1.30/rpm/
#             enabled: true
#             gpgkey: https://pkgs.k8s.io/core:/stable:/v1.30/rpm/repodata/repomd.xml.key
#             gpgcheck: true

#         - name: Install kubectl
#           ansible.builtin.dnf:
#             name: kubectl

#         - name: Install golang
#           ansible.builtin.dnf:
#             name: golang
