---
- name: Configure master
  hosts: master
  become: false
  gather_facts: false
  tags:
    - deploy
  tasks:
    - name: Check if helm is installed
      ansible.builtin.command: which helm
      register: which_helm
      ignore_errors: true
      failed_when: false
      changed_when: false

    - name: Download and install helm
      when: which_helm.rc != 0
      block:
        - name: Download helm installation script
          ansible.builtin.get_url:
            url: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
            dest: /home/ec2-user/get-helm-3.sh
            mode: "0700"

        - name: Install helm
          ansible.builtin.command: /home/ec2-user/get-helm-3.sh
          changed_when: true

    - name: Add spiderpool repo with helm
      kubernetes.core.helm_repository:
        name: spiderpool
        repo_url: https://spidernet-io.github.io/spiderpool

    - name: Install spiderpool with helm
      kubernetes.core.helm:
        name: spiderpool
        chart_ref: spiderpool/spiderpool
        namespace: kube-system
        set_values:
          - value: ipam.enableStatefulSet=false
          - value: multus.multusCNI.defaultCniCRName="ipvlan-eth0"

    - name: Pause for 30 seconds
      ansible.builtin.pause:
        seconds: 30

    - name: Remove default SpiderMultusConfig
      kubernetes.core.k8s:
        api_version: "spiderpool.spidernet.io/v2beta1"
        kind: SpiderMultusConfig
        namespace: kube-system
        name: ipvlan-eth0
        state: absent

    - name: Apply custom Spiderpool Multus ipvlan config
      kubernetes.core.k8s:
        definition: "{{ lookup('file', '../manifests/SpiderMultusConfig.yaml') | from_yaml_all }}"
        state: present

    - name: Add Spiderpool IP pools
      kubernetes.core.k8s:
        definition: "{{ lookup('file', '../manifests/SpiderIPPool.yaml') | from_yaml_all }}"
        state: present

    - name: Pause for 10 seconds
      ansible.builtin.pause:
        seconds: 10

- name: Deploy apps
  hosts: master
  become: false
  gather_facts: false
  tags:
    - deploy-apps
  tasks:
    - name: Create busybox deployment
      kubernetes.core.k8s:
        definition: "{{ lookup('file', '../manifests/Deployment-busybox.yaml') | from_yaml_all }}"
        state: present

    - name: Create nginx deployment
      kubernetes.core.k8s:
        definition: "{{ lookup('file', '../manifests/Deployment-nginx.yaml') | from_yaml_all }}"
        state: present

    - name: Pause for 30 seconds
      ansible.builtin.pause:
        seconds: 30

- name: Print pods and Spiderpool IP pools
  hosts: master
  become: false
  gather_facts: false
  tags:
    - print
  tasks:
    - name: Get pods
      ansible.builtin.command: kubectl get pods -owide
      register: kubectl_get_pods
      changed_when: false

    - name: Get Spiderpool IP pools
      ansible.builtin.command: kubectl get spiderippools.spiderpool.spidernet.io
      register: kubectl_get_spiderippools
      changed_when: false

    - name: Get busybox pod names
      ansible.builtin.command: kubectl get pods -oNAME --selector=run=busybox
      register: busybox_pod_names
      changed_when: false

    - name: Get IPs from inside of busybox pods
      ansible.builtin.command: "kubectl exec -it {{ item }} -- ip -4 addr show scope global"
      loop: "{{ busybox_pod_names.stdout_lines }}"
      register: busybox_pods_ips
      changed_when: false

    - name: Print pods
      ansible.builtin.debug:
        var: kubectl_get_pods.stdout_lines

    - name: Print Spiderpool IP pools
      ansible.builtin.debug:
        var: kubectl_get_spiderippools.stdout_lines

    - name: Print IPs from inside of pods
      ansible.builtin.debug:
        msg: "{{ item.stdout_lines }}"
      loop_control:
        label: "{{ item.item }}"
      loop: "{{ busybox_pods_ips.results }}"
