---
- name: Configure bastion and cluster
  hosts: bastion,cluster
  become: true
  gather_facts: false
  tags:
    - bastion-cluster
  tasks:
    - name: Install ssh key
      ansible.builtin.copy:
        src: "../id_ed25519"
        dest: "/home/ec2-user/.ssh/id_ed25519"
        mode: "0400"
        owner: ec2-user

    - name: Set hostname
      ansible.builtin.hostname:
        name: "{{ inventory_hostname }}"

    - name: Add cluster IPs to /etc/hosts
      ansible.builtin.lineinfile:
        dest: /etc/hosts
        regexp: '.*{{ item }}$'
        line: "{{ hostvars[item].ansible_host }} {{ item }}"
        state: present
      when: hostvars[item].ansible_host is defined
      with_items: "{{ groups.cluster }}"

    - name: Remove subscription manager
      ansible.builtin.dnf:
        name: subscription-manager
        state: absent

    - name: Install vim, tmux, git, bash-completion, python3-pip
      ansible.builtin.dnf:
        name:
          - vim
          - tmux
          - git
          - bash-completion
          - python3-pip
